ZJONSSON/clues

clues.js
test/minification-test.js

Here's an implementation of #9, along with a test.
Let me know what you think

Add support for partial array args

---

clues.js

resolve is in the standard Promise
tested locally @ZJONSSON

Rename fulfilled to resolve

---

bower.json
clues.js
package.json
test/null-logic-test.js

Avoid errors caused by `null` or `undefined` and avoid exposing the global object as `this` in `.apply`

Null logic

---

package.json
util/README.md
util/reptiles-server.js

This way a custom stringify function can be included in the 'options' object

Allows overriding of stringify fn via options

---

package.json
util/reptiles-server.js

Allows hash characters etc to be encoded

Use `decodeURIComponent` instead of `decodeURI`

---

clues.js
package.json
test/error-test.js

Fix: use Promise.try() to catch all errors

The try/catch did not pick up rejections with a stack

---

package.json
test/inject-test.js
util/README.md
util/inject.js

`inject` function that makes it easy to mock any endpoints in a logic tree by simply injecting the intended values in the right places

Add utility to inject

---

clues.js
package.json
test/promise-to-function.js

Previously: resolved to a function not the function resolution.  This is probably a rare edge case.

Fix: Promise that resolves to function

---

package.json
util/reptiles-server.js

closes https://github.com/ZJONSSON/clues/issues/37

Allow undefined `$global`

---

clues.js
util/reptiles-client.js

- `Promise.rejected` -> `Promise.reject`
- deferred constructor

Update deprecated syntax

---

util/reptiles-client.js

This one slipped past PR, simple fix

Fix overwrite function declaration

---

README.md

Fixes Incorrect unicode for character ᐅ

Fix incorrect dot alias unicode

---

clues.js
package.json

See: https://jsperf.com/date-now-vs-new-date

Use `Date.now()` instead of `new Date()`

---

clues.js
package.json
test/name-test.js

Copy the function name into a property of the promise

Retain function name in promise

---

README.md
circle.yml
clues.js
package.json
test/async-test.js

closes https://github.com/ZJONSSON/clues/issues/49

Parse functions with async keyword

---

package.json
test/inject-test.js
util/inject.js

Allow inject to create new children

---

clues.js
package.json
test/array-functions-test.js

This test failed until I made the change.  All other tests work.

Fix clues array evaluation when a context is provided

---

bower.json
clues.js
package.json
test/class-fn-test.js

We were failing to parse arguments from functions in ES6 classes

Support ES6 classes

---

util/reptiles-client.js

Not a huge change... thoughts?  There aren't reptiles-client tests as near as I can tell

Add support for "extra handler" to reptiles-client

---

package.json
test/inject-test.js
util/inject.js

When injecting a service we want `$original_service`

---

clues.js
package.json
test/class-fn-test.js

closes https://github.com/ZJONSSON/clues/issues/68

Constructor spaces

---

clues.js
package.json
test/error-test.js

Make sure "cache" flags get passed through error objects.

Add cache errors

---

.circleci/config.yml
circle.yml

Update the circleci config
https://circleci.com/gh/fijimunkii/clues/7

Circle 2 config

---

clues.js
test/class-fn-test.js

Support for multiline class functions
